/**
 *
 * $Id$
 */
package com.clafer4emf.clafer.validation;

import com.clafer4emf.clafer.CardInterval;
import com.clafer4emf.clafer.Clafer;
import com.clafer4emf.clafer.GCardInterval;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.clafer4emf.clafer.Clafer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClaferValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateIsAbstract(boolean value);
	boolean validateCElements(EList<Clafer> value);
	boolean validateCSuper(Clafer value);
	boolean validateCTarget(Clafer value);
	boolean validateCCardinality(CardInterval value);
	boolean validateCGroupCardinality(GCardInterval value);
}
